#+TITLE: Lab02 Tests
#+TESTY: PREFIX="lab02"
#+TESTY: REPORT_FRACTION=1
# #+TESTY: SHOW=1

* QUIZ: QUESTIONS.txt
This test determines if the answers in QUESTIONS.txt are correct. This
file must be edited so that the correct ( ) choices are replaced with
(X) AND no other changes are made to the file. If you are confident in
your answers but think you may have made inadvertent changes to
QUESTIONS.txt, you can try restoring it with the provided
QUESTIONS.txt.bk file.

The correct output for the test should be 
: -: OK

Note: the md5sum program is used for to verify and must be installed
to work.

#+TESTY: use_valgrind=0

#+BEGIN_SRC sh
>> ./test_quiz_filter QUESTIONS.txt | md5sum -c QUESTIONS.md5
-: OK
#+END_SRC


* CODE: list_main
#+TESTY: program='./list_main -echo'
#+TESTY: use_valgrind=1
#+TESTY: prompt='list>'

Runs various tests on the list_main application; copies of the tests
in test_list_main.org.

** Print then Exit
Print the empty list and exit

#+BEGIN_SRC sh
Linked List Demo
Commands:
  print:          shows the current contents of the list
  clear:          eliminates all elements from the list
  exit:           exit the program
  insert thing:   inserts the given string into the list
  get index:      get the item at the given index
  contains thing: determine if the given thing is in the list
                  (NOT YET IMPLEMENTED)
list> print
list> exit
#+END_SRC
** Insert 3 and Print
Add several items then print them back.

#+BEGIN_SRC sh
Linked List Demo
Commands:
  print:          shows the current contents of the list
  clear:          eliminates all elements from the list
  exit:           exit the program
  insert thing:   inserts the given string into the list
  get index:      get the item at the given index
  contains thing: determine if the given thing is in the list
                  (NOT YET IMPLEMENTED)
list> insert Mario
list> insert Luigi
list> insert Toad
list> print
0: Luigi
1: Mario
2: Toad
list> exit
#+END_SRC
** Get Command 
Checks that the ~get N~ command works correctly to return the value at
the Nth index of the list.

#+BEGIN_SRC sh
Linked List Demo
Commands:
  print:          shows the current contents of the list
  clear:          eliminates all elements from the list
  exit:           exit the program
  insert thing:   inserts the given string into the list
  get index:      get the item at the given index
  contains thing: determine if the given thing is in the list
                  (NOT YET IMPLEMENTED)
list> get 0
out of bounds
list> get 5
out of bounds
list> insert apple
list> insert pair
list> insert banana
list> print
0: apple
1: banana
2: pair
list> get 0
0: apple
list> get 1
1: banana
list> get 2
2: pair
list> get 3
out of bounds
list> exit
#+END_SRC
** Contains Items
Add several items then print them back.

#+BEGIN_SRC sh
Linked List Demo
Commands:
  print:          shows the current contents of the list
  clear:          eliminates all elements from the list
  exit:           exit the program
  insert thing:   inserts the given string into the list
  get index:      get the item at the given index
  contains thing: determine if the given thing is in the list
                  (NOT YET IMPLEMENTED)
list> insert Mario
list> insert Luigi
list> insert Toad
list> insert Bowser
list> insert Princess
list> contains Mario
'Mario' is present
list> contains Luigi
'Luigi' is present
list> contains Princess
'Princess' is present
list> contains Gumba
not found
list> contains Bob-omb
not found
list> exit
#+END_SRC
