#+TITLE: Lab08 Tests
#+TESTY: PREFIX="lab"
#+TESTY: REPORT_FRACTION=1
# #+TESTY: SHOW=1

* QUIZ: QUESTIONS.txt
This test determines if the answers in QUESTIONS.txt are correct. This
file must be edited so that the correct ( ) choices are replaced with
(X) AND no other changes are made to the file. If you are confident in
your answers but think you may have made inadvertent changes to
QUESTIONS.txt, you can try restoring it with the provided
QUESTIONS.txt.bk file.

The correct output for the test should be 
: -: OK

Note: the md5sum program is used for to verify and must be installed
to work.

#+TESTY: use_valgrind=0

#+BEGIN_SRC sh
>> ./test_quiz_filter QUESTIONS.txt | md5sum -c QUESTIONS.md5
-: OK
#+END_SRC


* CODE: order3_asm Program
Tests the contents of the order3_asm program to determine if it
operates correctly. To do so, it must allocate stack space correctly
and call some functions with the address of that stack space passed as
arguments to the function.

#+TESTY: program='./order3_asm'

#+BEGIN_SRC text
r t v: 12 13 17
q e d:  2  5  9
i j k: 24 27 29
#+END_SRC
